nome=str(input("Digite seu nome completo: ")).strip()
print("Analizando seu nome...")
print("Seu nome em maiúsculo é {}".format(nome.upper()))
print("Seu nome em minúsculo é {}".format(nome.lower()))
print("Seu nome têm ao todo {} letras".format(len(nome)-nome.count(" ")))
#print("Seu primeiro nome têm {} letras".format(nome.find(" ")))
separa=nome.split()
print("Seu primeiro nome é {} e ele têm {} letras".format(separa[0],len(separa[0])))